name: "CD (Entrega Continua)"

env: 
  VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID}}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches: [main, config-deploy]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3

      - name: Run Installation
        run: npm install

      - name: Run Deploy
        run: npm run deploy:prod

      - name: Deploy to Vercel
        run: npx vercel --prod --token=$VERCEL_TOKEN