name: "CI (Integração Contínua) - Lint Config"

#Configurações de Teste

on: 
    pull_request:
      branches: [ "opened", synchronize ]

# Definindo a execução
jobs:
    linter:
        runs-on: ubuntu-latest
        steps: 
            - uses: actions/checkout@v3
            - name: Run Installation
              run: npm install
            - name: Run Linter
              run: npm run lint